# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 22:05
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diffs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('before', models.CharField(max_length=200)),
                ('after', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('diff_percent', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('browser', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state_name', models.CharField(max_length=200)),
                ('state_desc', models.TextField()),
                ('state_json', models.TextField()),
                ('target', models.CharField(max_length=200)),
                ('target_type', models.CharField(max_length=200)),
                ('target_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HookCatcher.States'),
        ),
    ]
