# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0002_auto_20170111_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diff',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
