# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0003_auto_20170113_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diff',
            old_name='url',
            new_name='url1',
        ),
    ]
