# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0004_auto_20170113_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diff',
            old_name='url1',
            new_name='url',
        ),
    ]
