# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0006_auto_20170113_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diff',
            old_name='url',
            new_name='diff_img_url',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='browser',
            new_name='browser_type',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='state_img_url',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='target',
            new_name='github_source_id',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='target_id',
            new_name='github_source_type',
        ),
        migrations.RemoveField(
            model_name='diff',
            name='after',
        ),
        migrations.RemoveField(
            model_name='diff',
            name='before',
        ),
        migrations.RemoveField(
            model_name='state',
            name='state_id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='target_type',
        ),
        migrations.AddField(
            model_name='diff',
            name='control_state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='where_isControl', to='HookCatcher.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diff',
            name='test_state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='where_isTest', to='HookCatcher.Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
