# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0007_auto_20170123_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diff',
            old_name='control_state',
            new_name='control_state_img',
        ),
        migrations.RenameField(
            model_name='diff',
            old_name='test_state',
            new_name='test_state_img',
        ),
    ]
