# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0008_auto_20170125_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diff',
            old_name='test_state_img',
            new_name='source_state_img',
        ),
        migrations.RenameField(
            model_name='diff',
            old_name='control_state_img',
            new_name='target_state_img',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='github_source_id',
            new_name='git_branch_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='github_source_type',
            new_name='git_commit',
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='operating_system',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='git_pr_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='git_source_type',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
