# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0009_auto_20170125_2351'),
    ]

    operations = [
    ]
