# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0012_auto_20170208_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='state_img_url',
            field=models.CharField(max_length=200),
        ),
    ]
