# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0013_auto_20170221_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diff',
            name='diff_img_url',
            field=models.CharField(max_length=200),
        ),
    ]
