# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 01:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0014_auto_20170221_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='state_img_url',
            new_name='img_name',
        ),
        migrations.AlterField(
            model_name='diff',
            name='after_state_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whereAfterState', to='HookCatcher.Image'),
        ),
        migrations.AlterField(
            model_name='diff',
            name='before_state_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whereBeforeState', to='HookCatcher.Image'),
        ),
    ]
