# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 21:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0015_auto_20170404_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitHash', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitRepo', models.CharField(max_length=200)),
                ('gitPRNumber', models.IntegerField()),
                ('gitSourceCommit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asSourcePR', to='HookCatcher.Commit')),
                ('gitTargetCommit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asTargetPR', to='HookCatcher.Commit')),
            ],
        ),
        migrations.RenameField(
            model_name='diff',
            old_name='diff_img_url',
            new_name='diffImgName',
        ),
        migrations.RenameField(
            model_name='diff',
            old_name='diff_percent',
            new_name='diffPercent',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='browser_type',
            new_name='browserType',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_name',
            new_name='imgName',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='operating_system',
            new_name='operatingSystem',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='git_commit',
            new_name='gitBranch',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='git_source_name',
            new_name='gitRepo',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_desc',
            new_name='stateDesc',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='git_source_type',
            new_name='stateName',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_json',
            new_name='stateUrl',
        ),
        migrations.RemoveField(
            model_name='diff',
            name='after_state_img',
        ),
        migrations.RemoveField(
            model_name='diff',
            name='before_state_img',
        ),
        migrations.RemoveField(
            model_name='state',
            name='state_name',
        ),
        migrations.AddField(
            model_name='diff',
            name='sourceImg',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='asSourceDiff', to='HookCatcher.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diff',
            name='targetImg',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='asTargetDiff', to='HookCatcher.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='gitCommit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HookCatcher.Commit'),
            preserve_default=False,
        ),
    ]
