# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 19:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0017_auto_20170417_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diff',
            name='sourceImg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceDiff_set', to='HookCatcher.Image'),
        ),
        migrations.AlterField(
            model_name='diff',
            name='targetImg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetDiff_set', to='HookCatcher.Image'),
        ),
    ]
