# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 21:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0018_auto_20170417_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='gitPRCommit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prCommit_set', to='HookCatcher.Commit'),
        ),
    ]
