# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0020_auto_20170419_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imgName',
        ),
    ]
