# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 22:01
from __future__ import unicode_literals

from django.db import migrations, models

def transferFields(apps, schema_editor):
    State = apps.get_model("HookCatcher", "State")
    Commit = apps.get_model("HookCatcher", "Commit")

    for eachCommit in Commit.objects.all():
        eachState = eachCommit.state_set.all().first()
        if not eachState is None:
            eachCommit.gitRepo = eachState.gitRepo
            eachCommit.gitBranch = eachState.gitBranch
            eachCommit.save()
        else:
            eachCommit.delete()
class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0021_remove_image_imgname'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='gitRepo',
            field=models.CharField(null=True, max_length=200),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='commit',
            name='gitBranch',
            field=models.CharField(null=True, max_length=200),
            preserve_default=True,
        ),
        migrations.RunPython(transferFields),
        migrations.RemoveField(
            model_name='state',
            name='gitRepo',
        ),
        migrations.RemoveField(
            model_name='state',
            name='gitBranch',
        ),
    ]
