# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 23:03
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0022_auto_20170622_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imgName',
            field=models.CharField(null=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diff',
            name='diffImgName',
            field=models.CharField(null=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='diff',
            name='diffPercent',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), max_digits=6),
        ),
    ]
