# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0023_auto_20170622_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imgName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pr',
            name='gitPRNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
