# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0024_auto_20170711_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(),
        ),
    ]
