# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0025_auto_20170711_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='gitBranch',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commit',
            name='gitRepo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diff',
            name='diffImgName',
            field=models.CharField(max_length=200),
        ),
    ]
