# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0026_auto_20170711_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commit',
            name='gitHash',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='stateUUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
