# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0028_auto_20170711_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='device_res_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='device_res_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
