# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diff',
            name='diff_img_file',
            field=models.ImageField(max_length=500, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_file',
            field=models.ImageField(max_length=500, upload_to='img'),
        ),
    ]
