# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0002_auto_20170718_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diff',
            name='diff_img_file',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_file',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='img'),
        ),
    ]
