# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0005_auto_20170816_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='git_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
