# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='git_oauth_token',
            new_name='git_access_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='git_client_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='git_client_secret',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
