# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-20 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0008_auto_20170914_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
