# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 19:47
from __future__ import unicode_literals

import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0009_image_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_version', models.IntegerField()),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('status_code', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)])),
                ('git_source_commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_commit_in_PR', to='HookCatcher.Commit')),
                ('git_target_commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_commit_in_PR', to='HookCatcher.Commit')),
            ],
        ),
        migrations.RemoveField(
            model_name='pr',
            name='git_source_commit',
        ),
        migrations.RemoveField(
            model_name='pr',
            name='git_target_commit',
        ),
        migrations.AddField(
            model_name='state',
            name='host_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='login_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='login_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HookCatcher.PR'),
        ),
    ]
