# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 01:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0010_auto_20171031_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='status_code',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
    ]
