# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-09 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HookCatcher', '0011_auto_20171101_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
